using DataAccess.Concrete.EntityFramework.Contexts;
using Entities.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;

namespace WebAPI;

public static class DbInitializer
{
    public static async Task SeedAsync(BossBattleDbContext context, Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
        var creator = (RelationalDatabaseCreator)context.Database.GetService<IDatabaseCreator>();
        if (!await creator.ExistsAsync())
        {
            await creator.CreateAsync();
        }

        try
        {
            await creator.CreateTablesAsync();
        }
        catch
        {
            // Tablolar zaten mevcutsa devam et
        }

        try
        {
            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""AdminUsers"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Username"" character varying(60) NOT NULL,
                    ""PasswordHash"" character varying(256) NOT NULL,
                    ""PasswordSalt"" character varying(256) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""LastLoginAt"" timestamp with time zone
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AdminUsers_Username"" ON ""AdminUsers"" (""Username"");
            ");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[DB INIT] AdminUsers tablosu kontrol edilirken hata: {ex.Message}");
        }

        // Seed or update Admin User strictly from environment / configuration (ZERO HARDCODING)
        var adminUsername = configuration["Admin:Username"]
            ?? Environment.GetEnvironmentVariable("ADMIN_USERNAME");
        var adminPassword = configuration["Admin:Password"]
            ?? Environment.GetEnvironmentVariable("ADMIN_PASSWORD");

        if (!string.IsNullOrWhiteSpace(adminUsername) && !string.IsNullOrWhiteSpace(adminPassword))
        {
            var existingAdmin = await context.AdminUsers.FirstOrDefaultAsync(u => u.Username.ToLower() == adminUsername.Trim().ToLower());
            if (existingAdmin == null)
            {
                Core.Utilities.Security.HashingHelper.CreatePasswordHash(adminPassword, out var hash, out var salt);
                var newAdmin = new AdminUser
                {
                    Username = adminUsername.Trim(),
                    PasswordHash = hash,
                    PasswordSalt = salt,
                    CreatedAt = DateTime.UtcNow
                };
                await context.AdminUsers.AddAsync(newAdmin);
                await context.SaveChangesAsync();
                Console.WriteLine($"[ADMIN SEED] Admin '{adminUsername}' veritabanına başarıyla kaydedildi.");
            }
            else
            {
                if (!Core.Utilities.Security.HashingHelper.VerifyPasswordHash(adminPassword, existingAdmin.PasswordHash, existingAdmin.PasswordSalt))
                {
                    Core.Utilities.Security.HashingHelper.CreatePasswordHash(adminPassword, out var hash, out var salt);
                    existingAdmin.PasswordHash = hash;
                    existingAdmin.PasswordSalt = salt;
                    await context.SaveChangesAsync();
                    Console.WriteLine($"[ADMIN SEED] Admin '{adminUsername}' şifresi güncellendi.");
                }
            }
        }

        if (!await context.Rooms.AnyAsync())
        {
            var boss1 = new Boss
            {
                FullName = "Ahmet 'Synergy' Yılmaz",
                Headline = "Chief Disruption Officer | Ex-FAANG | Keynote Speaker | Forbes 30 Under 30 Finalist",
                LinkedInUrl = "https://www.linkedin.com/in/ahmet-synergy",
                AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=AhmetSynergy&glasses=eyepatch&hair=shortHairShortFlat",
                MaxHp = 100000,
                CurrentHp = 100000,
                IsDefeated = false,
                QuotesJson = "[\"Agree?\", \"Bunu hemen network'ümle paylaşıyorum!\", \"Sinerjimizi baltaladın!\", \"Growth mindset nerede dostum?!\", \"Pazartesi motivasyonumu düşürdün!\"]"
            };

            var boss2 = new Boss
            {
                FullName = "Zehra '500+ Connections' Kaya",
                Headline = "Prompt Architect | GenAI Evangelist | Coffee & B2B SaaS Lover | Open to Network",
                LinkedInUrl = "https://www.linkedin.com/in/zehra-network",
                AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=ZehraNetwork&glasses=round&hair=longHairBob",
                MaxHp = 50000,
                CurrentHp = 50000,
                IsDefeated = false,
                QuotesJson = "[\"Bugün bir mülakatta şunu öğrendim...\", \"Thoughts?\", \"Bana DM'den CV gönderin inceleyeyim!\", \"Bunu storylerimde paylaşacağım!\"]"
            };

            await context.Bosses.AddRangeAsync(boss1, boss2);
            await context.SaveChangesAsync();

            var room1 = new Room
            {
                Title = "Agile Guru Ahmet'i Linçleme Odası",
                Description = "Sürekli 'Agree?' yazıp insanlara akıl veren Ahmet'e yumruk atın!",
                RoomCode = "AGILE-AHMET",
                BossId = boss1.Id,
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            };

            var room2 = new Room
            {
                Title = "GenAI Evangelist Zehra Linç Meydanı",
                Description = "'ChatGPT ile 10 dakikada zengin oldum' diyen Zehra'yı durdurma vakti!",
                RoomCode = "GENAI-ZEHRA",
                BossId = boss2.Id,
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            };

            await context.Rooms.AddRangeAsync(room1, room2);
            await context.SaveChangesAsync();
        }
    }
}
